# Generated by Django 4.0 on 2023-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='TileNo',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
