# Generated by Django 4.0 on 2023-10-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_tile_tileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('highestscore', models.CharField(max_length=100)),
                ('history', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
